server:
     port : 8761
     
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    
    server:
     waitTimeInMsWhenSuncEmpty: 0  
     instance:
     hostname:
               LocalHost 
 